# Generated by Django 5.0.2 on 2024-02-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veg_name', models.TextField()),
                ('veg_type', models.CharField(max_length=100)),
                ('veg_color', models.CharField(max_length=100)),
                ('available_season', models.TextField()),
                ('veg_image', models.ImageField(upload_to='veges')),
            ],
        ),
    ]
