# Generated by Django 5.0.2 on 2024-02-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.TextField()),
                ('veg_included', models.CharField(max_length=100)),
                ('veg_color', models.CharField(max_length=100)),
                ('recipe_descrip', models.TextField()),
                ('veg_image', models.ImageField(upload_to='veges')),
            ],
        ),
        migrations.DeleteModel(
            name='vege',
        ),
    ]
