# Generated by Django 5.0.2 on 2024-02-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_recipe_delete_vege'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='veg_color',
        ),
    ]
