# Generated by Django 5.0.2 on 2024-03-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0006_department_student_id_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
